estacionameApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuario.urls')),
    path('comunas/', include('comunas.urls')),
    path('tiposUsuario/', include('tipoUsuario.urls')),
    path('estacionamientos/', include('estacionamiento.urls')),
    path('', include('web.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('register', views.postUsuario, name='register'),
    path('home', views.home, name='home'),
    path('estComuna/<str:id>', views.estComuna, name='estComuna'),
    path('admin_users', views.admin_users, name='admin_users'),
    path('admin_est', views.admin_est, name='admin_est'),
    path('eliminar_usuario/<id>', views.eliminar_usuario, name='eliminar_usuario'),

]

web/forms.py
from django import forms


class UsuarioForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    password = forms.CharField(max_length=12)
    email = forms.CharField(max_length=100)
    edad = forms.CharField(max_length=100)
    comuna = forms.CharField(max_length=100)


class LoginForm(forms.Form):
    email = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

class EstacionamientoForm(forms.Form):
    nombreContacto = forms.CharField(max_length=50)
    fonoContacto = forms.CharField(max_length=15)
    nombreComuna = forms.CharField(max_length=25)
    direccion = forms.CharField(max_length=90)
    imagenEstacionamiento = forms.FileField()

web/templates/web/admin_est.html
{% extends 'web/base.html' %}
{% load static %}
{% block contenido_body %}
    <div class="row mt-5 mb-5">
        <div class="col-12 text-center">
            <h1 class="text-white fw-bold">Lista de usuarios</h1>
        </div>
    </div>
    {% for est in responseEst %}
    <div class="col-md-12 d-flex justify-content-center">
        <div class="card mb-3" style="max-width: 380px;">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="{{ est.imagenEstacionamiento }}" class="banner-card" alt="foto_est">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"> Contacto: {{est.nombreContacto}}</h5>
                  <p class="card-text">Teléfono: {{est.fonoContacto}}</p>               
                  <p class="card-text">Dirección: {{est.direccion}}</p>               
                  <p class="card-text">Comuna: {{est.nombreComuna}}</p>
                  <a class="btn btn-warning">Editar</a>         
                  <a class="btn btn-danger">Eliminar</a>           
                </div>
              </div>
            </div>
        </div>            
    </div>
    {% endfor %}
{% endblock %}

web/templates/web/admin_users.html
{% extends 'web/base.html' %}
{% load static %}
{% block contenido_body %}
    <div class="row mt-5 mb-5">
        <div class="col-12 text-center">
            <h1 class="text-white fw-bold">Lista de usuarios</h1>
        </div>
    </div>
    {% for user in responseUser %}
    <div class="col-md-12 d-flex justify-content-center">
        <div class="card mb-3" style="width: 380px;">
            <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body">
                <h5 class="card-title"> Usuario: {{user.nombre}}</h5>
                <p class="card-text">Email: {{user.email}}</p>               
                <p class="card-text">Edad: {{user.edad}}</p>               
                <p class="card-text">tipo_usuario: {{user.tipo_usuario}}</p>
                <p class="card-text">Comuna: {{user.comuna}}</p>
                <a class="btn btn-warning">Editar</a>         
                <a class="btn btn-danger">Eliminar</a>         
                </div>
            </div>
            </div>
        </div>            
    </div>
    {% endfor %}
{% endblock %}

web/templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'web/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <title>Estacioname APP</title>
</head>
<body>

    <div class="container-fluid">

        {% block contenido_body %}
        {% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
        <script>
            Swal.fire({
                "title": "Felicitaciones",
                "text": "{{m}}",
                "icon": "success"
            })
        </script>
        {% endfor %}
    {% endif %}
    
</body>
</html>

web/templates/web/est_comuna.html
{% extends 'web/base.html' %}
{% load static %}
{% block contenido_body %}

    <div class="row">
        <div class="col-12 p-0">
            <img class=" banner-comuna" src="{{ responseComuna.imagenComuna }}" alt="">
        </div>
        <div class="col-12">
            {% if responseComuna %}
                <h1 class="text-warning fw-bold text-uppercase text-center mt-5">{{ responseComuna.nombreComuna }}</h1>
            {% endif %}
        </div>
        <div class="col-12">
            {% if responseComuna %}
                <h1 class="text-white text-center mt-5"> Lista de estacionamientos </h1>
            {% endif %}
        </div>
        <!--ira aqui un if?-->
        {% for est in responseEstacionamiento %}
        <div class="col-md-12 d-flex justify-content-center">
            <div class="card mb-3" style="max-width: 380px;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{{ est.imagenEstacionamiento }}" class="banner-card" alt="foto_est">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title"> Contacto: {{est.nombreContacto}}</h5>
                      <p class="card-text">Teléfono: {{est.fonoContacto}}</p>               
                      <p class="card-text">Dirección: {{est.direccion}}</p>               
                      <p class="card-text">Comuna: {{est.nombreComuna}}</p>
                      <a class="btn btn-warning">Tomar Arriendo</a>         
                    </div>
                  </div>
                </div>
            </div>            
        </div>
        {% endfor %}
    </div>



{% endblock %}

web/templates/web/home.html
{% extends 'web/base.html' %}
{% load static %}
{% block contenido_body %}

    {% if user_data.tipo_usuario == 'Arrendatario' %}
        <div class="row justify-content-center align-items-center mt-4">
            <div class="col-6 text-center">

                <h2 class="text-warning">Bienvenido</h2>
                

            </div>
            <div class="col-6 text-center">
                <p class="text-white">{{user_data.email}}</p>
            </div>
            <div class="col-12 text-center">
                <h2 class="text-warning mt-3">¿En que comuna deseas estacionar?</h2>
            </div>
            <div class="row d-flex flex-wrap">
                {% for comuna in responseComuna %}
                
                    <div class="col-4">
                        <a class="text-decoration-none" href="{% url 'web:estComuna' comuna.id %}">
                            <img class="img-fluid altura-comuna rounded-circle border border-warning mt-3" src="{{comuna.imagenComuna}}" alt="">
                            <p class="text-white text-center">{{comuna.nombreComuna}}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row ms-0 me-0 mt-5 p-0">
            <div class="col-12 m-0 p-0">
                <div id="mapa" class="container_mapa m-0"></div>
            </div>
        </div>
    {% endif %}

    {% if user_data.tipo_usuario == 'Arrendador' %}
        <div class="row mt-2">
            <div class="col-12 text-center">
                <h1 class="text-warning">Registra tu estacionamiento para ser arrendado</h1>
            </div>
        </div>
        <div class="row justify-content-center align-items-center ms-4 me-4 mt-5">
            <div class="col-md-6">
                <form action="{% url 'web:home' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <p> 
                        <input class="form-control rounded-5" id="id_nombreContacto" type="text" name="nombreContacto" placeholder="Nombre de contacto" required>
                    </p>
                    <br>
                    <p>
                        <input class="form-control rounded-5" id="id_fonoContacto" type="text" name="fonoContacto"  placeholder="Fono Contacto" required>
                    </p>
                    <br>
                    <br>
                    <p>
                        <label class="text-white" for="nombreComuna">Comuna</label>
                        <select name="nombreComuna" id="comuna" required>
                            {% for comuna in responseComuna %}
                                <option value="{{comuna.nombreComuna}}">{{comuna.nombreComuna}}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <br>
                    <p>
                        <input class="form-control rounded-5" id="id_direccion" type="text" name="direccion" placeholder="Direccion" required>
                    </p>
    
                    <p> 
                        <label class="text-white">Foto de estacionamiento</label>
                        <input class="form-control rounded-5" id="id_imagenEstacionamiento" type="file" name="imagenEstacionamiento" required>
                    </p>
                    <br>

                    <div class="text-center">
                        <button type="submit" class="btn btn-warning p-3 rounded-5">Registrar estacionamiento</button>
                    </div>
                    
                </form>
        
            </div>
        </div>
    {% endif %}

    {% if user_data.tipo_usuario == 'Administrador' %}
        <div class="row mt-2">
            <div class="col-12 text-center">
                <h1 class="text-white">Bienvenido {{user_data.email}}</h1>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12 text-center">
                <h3 class="text-warning">Administra los registros</h3>
            </div>
        </div>
        <!--card adm users-->
        <div class="col-md-12 d-flex justify-content-center">
            <div class="card mb-3" style="max-width: 380px;">
                <div class="row g-0">
                <div class="col-md-4">
                    <img src="../../static/web/img/users.jpg" class="banner-card" alt="foto_est">
                </div>
                <div class="col-md-8 text-center">
                    <div class="card-body">
                    <h5 class="card-title">Usuarios</h5>            
                    <a href="{% url 'web:admin_users' %}" class="btn btn-warning">Administrar</a>         
                    </div>
                </div>
                </div>
            </div>            
        </div>
        <!--card adm est-->
        <div class="col-md-12 d-flex justify-content-center mt-5">
            <div class="card mb-3" style="max-width: 380px;">
                <div class="row g-0">
                <div class="col-md-4">
                    <img src="../../static/web/img/est_admin.png" class="banner-card" alt="foto_est">
                </div>
                <div class="col-md-8 text-center">
                    <div class="card-body">
                    <h5 class="card-title">Estacionamientos</h5>            
                    <a href="{% url 'web:admin_est' %}" class="btn btn-warning">Administrar</a>         
                    </div>
                </div>
                </div>
            </div>            
        </div>
    {% endif %}




    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAiM-uOjAVu38ma8Eq0Wi6cF4LrW4mbGQ&libraries=places&callback=initMap" defer></script>
    <script src="{% static 'web/js/map.js'%}"></script>

{% endblock %}

web/templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}
{% block contenido_body %}

    <div class="row justify-content-center align-items-center text-center mt-5 pt-2">
        <div class="col-12">
            <h1 class="fw-bold text-warning">Estacioname APP</h1>
        </div>
        <div class="col-12 pt-2">
            <img class="img-fluid" src="{% static 'web/img/logoapp.png' %}" alt="">
        </div>
        <div class="col-12 text-center pt-5">
            <a href="{% url 'web:register' %}" class="btn btn-warning p-3 rounded-5 me-5">Registrate</a>
            <a href="{% url 'web:login' %}" class="btn btn-warning p-3 rounded-5">Ingresar</a>
        </div>
    </div>




{% endblock %}

web/templates/web/login.html
{% extends 'web/base.html' %}
{% load static %}
{% block contenido_body %}

    <div class="row m-0 p-0 text-center mt-2">
        <div class="col-12">
            <h1 class=" fw-bold text-warning">Estacioname APP</h1>
        </div>
        <div class="col-12">
            <img class="img-fluid" src="{% static 'web/img/logo.png' %}" alt="logo-est">
        </div>
        <div class="col-12">
            <h1 class="text-white fw-bold">Login</h1>
        </div>
    </div>

    <br>
    <br>

    <div class="row justify-content-center align-items-center ms-4 me-4 mt-1">
        <div class="col-md-6">
            <form method="post" action="{% url 'web:login' %}">
                {% csrf_token %}
                <input class="form-control rounded-5" id="id_email" type="email" name="email" maxlength="100" placeholder="email" required>
                <br>
                <input class="form-control rounded-5" id="id_password" type="password" name="password" maxlength="100" placeholder="password" required>
                <br>
                <div class="text-center pt-3">
                    <button type="submit" class="btn btn-warning p-3 rounded-5">Iniciar sesion</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

web/templates/web/register.html
{% extends 'web/base.html' %}
{% load static %}
{% block contenido_body %}

    <div class="row m-0 p-0 text-center mt-2">
        <div class="col-12">
            <h1 class=" fw-bold text-warning">Estacioname APP</h1>
        </div>
        <div class="col-12">
            <img class="img-fluid" src="{% static 'web/img/logo.png' %}" alt="logo-est">
        </div>
        <div class="col-12">
            <h1 class="text-white fw-bold">Registro de usuario</h1>
        </div>
    </div>

    <div class="row justify-content-center align-items-center ms-4 me-4 mt-1">
        <div class="col-md-6">
            <form action="{% url 'web:register' %}" method="post">
                {% csrf_token %}
                
                <p> 
                    <input class="form-control rounded-5" id="id_nombre" type="text" name="nombre" maxlength="100" placeholder="Nombre" required>
                </p>
                <br>
                <p>
                    <input class="form-control rounded-5" id="id_password" type="password" name="password" maxlength="12" placeholder="Password" required>
                </p>
                <br>
                <p>
                    <input class="form-control rounded-5" id="id_email" type="email" name="email" maxlength="100" placeholder="Email" required>
                </p>
                <br>
                <p> 
                    <input class="form-control rounded-5" id="id_edad" type="text" name="edad" maxlength="100" placeholder="Edad" required>
                </p>
                <br>
                <p>
                    <label for="tipoUsuario" class="text-white">Tipo de usuario</label>
                    <select name="tipoUsuario" id="tipoUsuario" required>
                        {% for tipoUsuario in responseTipoUser %}
                            <option value="{{tipoUsuario.tipo_Usuario}}">{{tipoUsuario.tipo_Usuario}}</option>
                        {% endfor %}
                    </select>
                </p>
                <br>
                <p> 
                    <input class="form-control rounded-5" id="id_comuna" type="text" name="comuna" maxlength="100" placeholder="Comuna" required>
                </p>
                <br>
                <p class="text-center">
                    <input type="checkbox" id="terms" name="terminos" value="term">
                    <label for="terminos" class="text-white" >I agree with <a href="" class="text-decoration-none fw-bold text-info">Terms and Conditions</a></label><br>
                </p>

                <div class="text-center">
                    <button type="submit" class="btn btn-warning p-3 rounded-5">Registrar usuario</button>
                </div>
                
            </form>
    
        </div>
    </div>
{% endblock %}






            